version: '2'
services:
  go-pttbbs:
    image: pttofficialapps/go-pttbbs:v0.4.7
    ports:
      - "127.0.0.1:8888:8888"
      - "127.0.0.1:48763:48763"
    restart: always
    volumes:
      - ${BBSHOME}:/home/bbs
  mongo:
    image: mongo:4.4.2
    restart: always
    volumes:
      - /var/lib/mongo:/data
      - /var/lib/mongo/db:/data/db
      - /var/lib/mongo/configdb:/data/configdb
  redis:
    image: redis:6.0.9-alpine
    restart: always
  openbbs-middleware:
    image: pttofficialapps/go-openbbsmiddleware:v0.5.2
    ports:
      - "127.0.0.1:3457:3457"
    volumes:
      - ${STATIC_DIR}:/static
    restart: always
