name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Start Redis
      uses: supercharge/redis-github-action@1.1.0
      with:
        redis-version: 6

    - name: MongoDB in GitHub Actions
      uses: supercharge/mongodb-github-action@1.7.0
      with:
       mongodb-version: 4.4

    - name: check mongo
      run: mongo localhost:27017 --eval "db.test.find()"

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.16

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        args: --verbose
        version: v1.45.2

    - name: Build
      run: make

    - name: TestQueueCommentDBCS
      run: go test -v ./... -run TestQueueCommentDBCS -tags queue

    - name: Testing
      run: make test
      env:
        TAGS: noqueue

    - name: Upload coverage report
      uses: codecov/codecov-action@v1
