name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Start Redis
      uses: supercharge/redis-github-action@1.1.0
      with:
        redis-version: 6

    - name: MongoDB in GitHub Actions
      uses: supercharge/mongodb-github-action@1.3.0
      with:
       mongodb-version: 4.4

    - name: check mongo
      run: mongo localhost:27017 --eval "db.test.find()"

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.16

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v2
      with:
        args: --verbose
        version: v1.41.1

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi

    - name: Build
      run: go build -v ./...

    - name: TestQueueCommentDBCS
      run: go test -v ./... -run TestQueueCommentDBCS

    - name: Test
      run: go test -v ./... -tags noqueue

    - name: Coverage-queue
      run: go test ./... -run TestQueueCommentDBCS -cover

    - name: Coverage
      run: go test ./... -tags noqueue -cover -coverprofile cover.out

    - name: Upload coverage report
      uses: codecov/codecov-action@v1
      with:
        file: cover.out
